from datetime import datetime
from typing import Protocol

from app.schemas import Alert, AlertStatus, Report, Severity


class AlertStore(Protocol):
    def save_raw_alert(self, alert: Alert) -> str: ...
    def get_alert(self, alert_id: str) -> Alert: ...
    def list_alerts(
        self, status: AlertStatus | None, since: datetime | None, limit: int = 100
    ) -> list[Alert]: ...
    def update_alert_status(self, alert_id: str, status: AlertStatus) -> None: ...
    def save_report(self, report: Report) -> str: ...
    def get_report(self, report_id: str) -> Report: ...
    def get_report_for_alert(self, alert_id: str) -> Report | None: ...
    def list_reports(
        self, since: datetime | None, min_severity: Severity | None
    ) -> list[Report]: ...
