from datetime import datetime
from typing import Protocol

from app.integration.models import AgentContext, RuleMetadata, SearchQuery, SearchResult
from app.schemas import Alert


class SIEMConnector(Protocol):
    def health_check(self) -> bool: ...
    def pull_alerts(self, since: datetime, until: datetime | None = None, limit: int = 500) -> list[Alert]: ...
    def search(self, query: SearchQuery) -> SearchResult: ...
    def get_agent_context(self, agent_id: str) -> AgentContext: ...
    def get_rule_metadata(self, rule_id: str) -> RuleMetadata: ...
